# Generated by Django 5.2.5 on 2025-08-25 17:24

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_position_profile_delete_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                null=True,
                upload_to="accounts/profiles/avatars/",
                verbose_name="Avatar",
            ),
        ),
    ]
