# Generated by Django 5.2.5 on 2025-08-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0002_remove_task_is_completed_task_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created_at",)},
        ),
    ]
