# Generated by Django 5.2.5 on 2025-08-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0003_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="position",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
