# Generated by Django 5.2.5 on 2025-08-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0004_task_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ("position",)},
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="flowdesk.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="list",
            constraint=models.UniqueConstraint(
                fields=("board", "position"), name="unique_list_position_per_board"
            ),
        ),
    ]
