# Generated by Django 5.2.5 on 2025-08-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0005_alter_list_options_alter_workspacemember_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("position",)},
        ),
        migrations.RemoveConstraint(
            model_name="list",
            name="unique_list_position_per_board",
        ),
    ]
