# Generated by Django 5.2.5 on 2025-08-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0007_remove_task_members_board_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="blocking_tasks",
            field=models.ManyToManyField(related_name="tasks", to="flowdesk.task"),
        ),
    ]
