# Generated by Django 5.2.5 on 2025-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0008_task_blocking_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="blocking_tasks",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="flowdesk.task"
            ),
        ),
    ]
