# Generated by Django 5.2.5 on 2025-08-25 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flowdesk", "0009_alter_task_blocking_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
